hr-mitra/config/routes.rb
Rails.application.routes.draw do



  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # resources :employees 
  resources :employees  do
    get 'graph', on: :collection
  end

  resources :documents

  # resources :departments, only: [:index]

  # get '/departments/index', to: 'departments#index'
  # get '/employees/graph', to: 'employees#graph'

  root 'pages#index'
  get 'about-us' => 'pages#about_us'
  get 'services' => 'pages#services'
  get 'contact' => 'pages#contact'
  get 'privacy-policy' => 'pages#privacy_policy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

hr-mitra/app/models/employee.rb
class Employee < ApplicationRecord

    has_many :documents
    # dependent: :delete_all
  # The model name for has_many must be plular



    validates :F_Name, :L_Name, :Department, :Adreess, :date_of_birth, presence:true
    validates :Mail_Id, :Contact_No, presence:true, uniqueness:true 

    def name
        "#{self.F_Name} #{self.L_Name}".strip
    end    
    # here ".strip" is to reduce the /n or space between 

    def name_mail
      "#{self.F_Name} (#{self.Mail_Id})"
    end

end
 

hr-mitra/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    # before_action helps to follow the DRY code rule 

    before_action :set_employee, only: [:edit, :show, :update, :destroy]




    def index
        @employee=Employee.all()
    end
    def new
        @employee=Employee.new
    end
    def create
        @employee=Employee.new(employee_params)

        if @employee.save
            redirect_to employees_path, notice: "Employee has been added successfully"
        else 
            render :new
        end
    end


    def edit
    end

    def show
    end

    def graph
        @department_data = EmployeeGraphService.new.department_data
    end
    # def graph
    #     @employee= Employee.new(department: params[:employee][:department])    
    # end


    def update
        if @employee.update(employee_params)
            redirect_to employees_path, notice: "Employee has been updated successfully"
        else 
            render :edit
        end
    end

    def destroy
        if @employee.destroy
            redirect_to employees_path, notice: "Employee has been deleted successfully"
        end
    end

    
    private

    def employee_params
        params.require(:employee).permit(:F_Name,:L_Name,:Department,:Adreess,:Mail_Id,:Contact_No, :date_of_birth, :date_of_joining)
    end

    def set_employee
        @employee = Employee.find(params[:id])
        # same query in edit show destroy update

        # Error handling

        rescue ActiveRecord::RecordNotFound => error
            redirect_to employees_path, alert: error
    end
end 

hr-mitra/app/views/employees/edit.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5 m-auto"  style="width: 90%;">
  <div class="card-body">
    <h1 class="text-center">Update the Employee</h1>
    </div>
</div>


<%= render 'shared/form'%>







  

 
  

hr-mitra/app/views/employees/graph.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5 m-auto"  style="width: 90%;">
  <div class="card-body">
    <h1 class="text-center">Human Resources Chart</h1>
    </div>
</div>



<div class="container" style = "height: 350px; margin-top:100px">
<%= column_chart @department_data %>   
</div>
<%# <%= bar_chart @department_data %> 

<%# <%= render 'shared/form'%>


<div class="col-lg-12">
  <div class="col-md-12 d-grid d-md-flex justify-content-end">
      <%= link_to "Back", employees_path,class:"btn btn-primary"%>
  </div>
  </div>
  </div>

hr-mitra/app/views/employees/index.html.erb
<!--
<div class="alert alert-success" role="alert">
    <%= flash[:notice]%>
</div>
-->
<%= render "shared/flash"%>



<div class="card mt-5 mb-5 m-auto" >
  <div class="card-body">
    <h1 class="text-center">Employees List</h1>
    </div>
</div>

<!--

    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        View List In
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li><%= link_to "Table", employees_path(view_type: "table"), class:"dropdown-item  "%></li>
      <li><%= link_to "Accordain", employees_path(view_type: "accordain"), class:"dropdown-item  "%></li>
      </ul>
    </div>
-->


<div class="row">
<div class="col">
<%= link_to "Table", employees_path(view_type: "table"), class:"btn btn-outline-warning bg-success "%>
<%= link_to "Accordain", employees_path(view_type: "accordain"), class:"btn btn-outline-warning bg-success"%>
</div>
</div>


<% if params[:view_type] != "accordain"%>
<table class="table table-hover table-striped table-bordered mt-3 ml-5 m-auto">
  <thead class="table-dark">
    <tr>
      <th>#</th>
      <%# <th>First</th>
      <th>Last</th> %>
      <th>Name</th>
      <th>Department</th>
      <th>Adreess</th>
      <th>Mail_Id</th>
      <th>Contact_No</th>
      <th>Date_of_Birth</th>
      <th>Date_of_Joining</th>
      <th style="width:14%">Action</th>
    </tr>
  </thead>
  <tbody>
  <script>
      console.log(1)
      </script>
  <% @employee.each do |e| %>
    <tr>
      <td><%= e.id %></td>
      <%# <td><%= e.F_Name </td>%>
      <%# <td><%= e.L_Name </td>  %> 
      <td><%= e.name %></td>
      <td><%= e.Department %></td>
      <td><%= e.Adreess %></td>
      <td><%= e.Mail_Id %></td>
      <td><%= e.Contact_No %></td>
      <td><%= e.date_of_birth%></td>
      <td><%= e.date_of_joining%></td>
      <td>
      <%= link_to "Edit", edit_employee_path(e), class:"btn btn-outline-warning bg-primary btn-sm"%>
      <%= link_to "View", employee_path(e), class:"btn btn-outline-warning bg-secondary btn-sm"%>
      <%= link_to "Delete", employee_path(e), class:"btn btn-outline-warning bg-danger btn-sm", method: :delete, data: {confirm: 'Are you sure to delete this employee?'}%>
      </td>
    <%end %>
    </tr>
  </tbody>
</table>
<%end %>








<% if params[:view_type].present?  &&  params[:view_type] == "accordain"%>
<div class="accordion mt-5" id="accordionExample">
  <% @employee.each do |e| %>
  <div class="accordion-item">
    <h2 class="accordion-header" id="heading<%= e.id%>">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= e.id%>" aria-expanded="true" aria-controls="collapse<%= e.id%>">
        <%= e.name_mail%>
      </button>
    </h2>
    <div id="collapse<%= e.id%>" class="accordion-collapse collapse" aria-labelledby="heading<%= e.id%>" data-bs-parent="#accordionExample">
      <div class="accordion-body">

        <div class="col-lg-12">
          <div class="card mt-5 mb-5 m-auto"  style="width: 90%;">
            <div class="card-body">
              <h1 class="text-center">View Employee Details</h1>
            </div>
          </div>



          <div class="row ">
            <div class="col-md-6">
              <h3> First Name <h3>
              <%= e.F_Name%>
            </div>
            <div class="col-md-6">
              <h3> Last Name <h3>
              <%= e.L_Name%>
            </div>
          </div>

          <div class="col-12 mt-5">
            <h3> Address <h3>
            <%= e.Adreess%>
          </div>

          <div class="row mt-5">
            <div class="col-md-6">
              <h3> Mail ID <h3>
              <%= e.Mail_Id%>
            </div>

            <div class="col-md-6">
              <h3> Contact_No <h3>
              <%= e.Contact_No%>
            </div>
          </div>

          <div class="row mt-5">
            <div class="col-md-6">
              <h3> Date_of_Birth <h3>
            <%= e.date_of_birth%>
          </div>
          <div class="col-md-6">
            <h3> Date_of_Joining <h3>
            <%= e.date_of_joining%>
          </div>
        </div>

        <div class="col-md-4 mt-5 mb-4">
          <h3> Department <h3>
          <%= e.Department%>
        </div>


        <% if e.documents.present? %>
          <div class="row mt-5">
            <h2 class="text-center">Employee Documents</h2>
              <% e.documents.each do |d| %>
          </div>
          <div class="card mt-4">
            <div class="card-body">
              <div class="row">
                <% if d.doc_upload.attached? %>
                  <div class="col-lg-4">
                  <%= image_tag d.doc_upload, class:"img-fluid"%>
                  </div>
                <%end%>
                <div class="col-lg-4">
                  <p class="lead"><%= d.name %></p>
                </div>
                <div class="col-lg-4">
                  <p class="lead"><%= d.doc_type %></p>
                </div>
              </div>
            </div>
        <%end%>
      </div>
  
<%# <!-- %>
<%# --> %>
<%end%>




<div class="col-lg-12">
  <div class="col-md-12 mt-5 m-auto"  style="width: 90%;">
      <%= link_to "Edit", edit_employee_path(e), class:"btn btn-outline-warning bg-primary"%>
  </div>
    <%# <button type="submit" class="btn btn-primary">Sign in</button> %>
  <div class="col-md-12 d-grid d-md-flex justify-content-end m-auto"  style="width: 90%;  ">
      <%= link_to "Delete", employee_path(e), class:"btn btn-outline-warning bg-danger", method: :delete, data: {confirm: 'Are you sure to delete this employee?'}%>
  </div>
  </div>
  </div>
 
      </div>
    </div>
  </div>
  <% end %>
</div>

    <%end %>




<%# <%= column_chart @graph_data %>



<div class="d-grid gap-2 mt-5 d-md-flex justify-content-md-end">

<%= link_to "Add New Employee", new_employee_path, class:"btn btn-primary"%>
<%# <%= link_to "Resources_Graph", graph_path, class:"btn btn-outline-warning bg-success"%> 
</div>

<%# 
scope="col"
scope="col"
scope="col"
scope="col"
scope="col"
scope="col"
scope="col" %>

hr-mitra/app/views/employees/new.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5 m-auto"  style="width: 90%;">
  <div class="card-body">
    <h1 class="text-center">Add New Employees</h1>
    </div>
</div>


<%= render 'shared/form'%>


  

 
  

hr-mitra/app/views/employees/show.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5 m-auto"  style="width: 90%;">
  <div class="card-body">
    <h1 class="text-center">View Employee Details</h1>
    </div>
</div>



<div class="row ">
  <div class="col-md-6">
<h3> First Name <h3>
<%= @employee.F_Name%>


  </div>
  <div class="col-md-6">
<h3> Last Name <h3>
<%= @employee.L_Name%>
  </div>
  </div>

  <div class="col-12 mt-5">
<h3> Address <h3>
<%= @employee.Adreess%>
  </div>

  <div class="row mt-5">
  <div class="col-md-6">
<h3> Mail ID <h3>
<%= @employee.Mail_Id%>
  </div>

  <div class="col-md-6">
<h3> Contact_No <h3>
<%= @employee.Contact_No%>
  </div>
  </div>

  <div class="row mt-5">
  <div class="col-md-6">
<h3> Date_of_Birth <h3>
<%= @employee.date_of_birth%>
  </div>
  <div class="col-md-6">
<h3> Date_of_Birth <h3>
<%= @employee.date_of_joining%>
  </div>
  </div>

  <div class="col-md-4 mt-5 mb-4">
<h3> Department <h3>
<%= @employee.Department%>
  </div>


<% if @employee.documents.present? %>
  <div class="row mt-5">
    <h2 class="text-center">Employee Documents</h2>
    <% @employee.documents.each do |d| %>

  </div>
  <div class="card mt-4">
    <div class="card-body">
      <div class="row">
        <% if d.doc_upload.attached? %>
        <div class="col-lg-4">
          <%= image_tag d.doc_upload, class:"img-fluid"%>
        </div>
        <%end%>
        <div class="col-lg-4">
          <p class="lead"><%= d.name %></p>
        </div>
        <div class="col-lg-4">
          <p class="lead"><%= d.doc_type %></p>
        </div>
      </div>
    </div>
  <%end%>
  </div>
<%end%>








  <div class="col-lg-12">
  <div class="col-md-12 mt-5">
      <%= link_to "Edit", edit_employee_path, class:"btn btn-primary" %>
  <div class="col-md-12 d-grid d-md-flex justify-content-end">
      <%= link_to "Back", employees_path,class:"btn btn-primary"%>
  </div>
  </div>
  </div>