hr-mitra/config/routes.rb
Rails.application.routes.draw do



  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # resources :employees 
  resources :employees  do
    get 'graph', on: :collection
  end

  resources :documents

  # resources :departments, only: [:index]

  # get '/departments/index', to: 'departments#index'
  # get '/employees/graph', to: 'employees#graph'

  root 'pages#index'
  get 'about-us' => 'pages#about_us'
  get 'services' => 'pages#services'
  get 'contact' => 'pages#contact'
  get 'privacy-policy' => 'pages#privacy_policy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

hr-mitra/app/models/document.rb
class Document < ApplicationRecord

  Doc_Types = ["Marksheet", "Photo_ID","Personal_ID","Address Proof","Others"].freeze

  has_one_attached :doc_upload

  belongs_to :employee, foreign_key: :employee_id
  # The model name for belongs_to must be singular

  validates :name, :doc_type, presence: true
end

hr-mitra/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

    before_action :set_document, only: [:edit, :show, :update, :destroy]




    def index
        @documents=Document.all()
    end
    def new
        @document=Document.new
    end
    def create
        @document=Document.new(document_params)

        if @document.save
            redirect_to documents_path, notice: "Document has been added successfully"
        else 
            render :new
        end
    end


    def edit
    end

    def show
    end


    def update
        if @document.update(document_params)
            redirect_to documents_path, notice: "Document has been updated successfully"
        else 
            render :edit
        end
    end

    def destroy
        if @document.destroy
            redirect_to documents_path, notice: "Document has been deleted successfully"
        end
    end

    
    private

    def document_params
        params.require(:document).permit(:name,:doc_type,:employee_id,:doc_upload)
    end

    def set_document
        @document = Document.find(params[:id])
        # same query in edit show destroy update

        # Error handling

        rescue ActiveRecord::RecordNotFound => error
            redirect_to documents_path, alert: error
    end

end

hr-mitra/app/views/documents/edit.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5 m-auto"  style="width: 90%;">
  <div class="card-body">
    <h1 class="text-center">Update the Document</h1>
    </div>
</div>


<%= render 'shared/docform'%>

  

 
  

hr-mitra/app/views/documents/index.html.erb
<%= render "shared/flash"%>



<div class="card mt-5 mb-5 m-auto" >
  <div class="card-body">
    <h1 class="text-center">Document Uploaded List</h1>
    </div>
</div>



<table class="table table-hover table-striped table-bordered ml-5 m-auto">
  <thead class="table-dark">
    <tr>
      <th>#</th>
      <%# <th>First</th>
      <th>Last</th> %>
      <th>Document Name</th>
      <th>Document Type</th>
      <th>Employee Name</th>
      <th>Employee ID</th>
      <th style="width:14%">Action</th>
    </tr>
  </thead>
  <tbody>
  <script>
    console.log(1)
    </script>
    

  <% @documents.each do |d| %>
    <tr>
      <td><%= d.id %></td>
      <%# <td><%= e.F_Name </td>%>
      <%# <td><%= e.L_Name </td>  %> 
      <td><%= d.name %></td>
      <td><%= d.doc_type %></td>
      <td><%= link_to d.employee.name, employee_path(d.employee) %></td>
      <td><%= d.employee.id %></td>
      <td>
         <%= link_to "Edit", edit_document_path(d), class:"btn btn-outline-warning bg-primary btn-sm"%>
      <%= link_to "View", document_path(d), class:"btn btn-outline-warning bg-secondary btn-sm"%>
      <%= link_to "Delete", document_path(d), class:"btn btn-outline-warning bg-danger btn-sm", method: :delete, data: {confirm: "Are you sure to delete the employee's document?"}%>
      </div>
      </td>
      </tr>  
    <% end %>
    
  </tbody>
</table>

<div class="d-grid gap-2 mt-5 d-md-flex justify-content-md-end">
<%= link_to "Add New Document", new_document_path, class:"btn btn-primary"%>
</div>

hr-mitra/app/views/documents/new.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5 m-auto"  style="width: 90%;">
  <div class="card-body">
    <h1 class="text-center">Add Documents Employees</h1>
    </div>
</div>


<%= render 'shared/docform'%>


  

 
  

hr-mitra/app/views/documents/show.html.erb
<div class="col-lg-12">
  <div class="card mt-5 mb-5 m-auto"  style="width: 90%;">
    <div class="card-body">
      <h1 class="text-center">View Employee Details</h1>
    </div>
  </div>
</div>



<div class="row ">
  <div class="col-md-6">
    <h3> Document Name </h3>
      <%= @document.name%>
  </div>

  <div class="col-md-6">
    <h3> Document Type </h3>
    <%= @document.doc_type%>
  </div>
</div>


<div class="row mt-5">
  <div class="col-md-6">
    <h3> Employee ID</h3>
    <%= @document.employee_id%>
  </div>

  <div class="col-md-6">
    <h3> Employee Name</h3>
    <%= @document.employee.name%>
  </div>
</div>



  <% if @document.doc_upload.attached? %>
  <%# <div class="img mt-5 "> %>
    <%= image_tag @document.doc_upload,class:"img mt-5 mx-auto d-block",style:" width: 40%;"%>
    <h3 class=" d-grid d-md-flex justify-content-center mt-2"> Document Image </h3>
  <%# </div>   %>
  <% end %>

    
<div class="col-lg-12">
  <div class="col-md-12 mt-5">
      <%= link_to "Edit", edit_document_path, class:"btn btn-primary" %>
      <div class="col-md-12 d-grid d-md-flex justify-content-end">
          <%= link_to "Back", documents_path,class:"btn btn-primary"%>
      </div>
  </div>
</div>