hr-mitra/config/routes.rb
Rails.application.routes.draw do



  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # resources :employees 
  resources :employees  do
    get 'graph', on: :collection
  end

  resources :documents

  # resources :departments, only: [:index]

  # get '/departments/index', to: 'departments#index'
  # get '/employees/graph', to: 'employees#graph'

  root 'pages#index'
  get 'about-us' => 'pages#about_us'
  get 'services' => 'pages#services'
  get 'contact' => 'pages#contact'
  get 'privacy-policy' => 'pages#privacy_policy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

hr-mitra/app/views/shared/_design.html.erb
<%= link_to "Home" ,root_path, target:"_blank", style:'color:grey'%>
<%= link_to "About Us" ,about_us_path, target:"_blank", style:'color:red'%>
<%= link_to "Privacy Policy" ,privacy_policy_path, target:"_blank", style:'color:red'%>
<%= link_to "Contact" ,contact_path, target:"_blank", style:'color:red'%>
<%= link_to "Services" ,services_path, target:"_blank", style:'color:red'%>
\
<%# target:"_blank" for the link to open on new page %>

hr-mitra/app/views/shared/_docform.html.erb
<%= form_with model: @document, local: true do |form|%>




<div class=" d-grid d-md-flex justify-content-center">
<div class=" col-lg-6 mb-4">
        <%= form.label :name %>
         <%= form.text_field :name, class:"form-control"%>
        <% @document.errors.full_messages_for(:name).each do |message|%>
         <p class="text-danger"><%= message%></p>
         <%end %>
</div>
</div>


<div class=" d-grid d-md-flex justify-content-center">
<div class="col-lg-6 mb-4">
    <%= form.label :doc_type %>
    <%= form.select :doc_type, options_for_select(Document::Doc_Types, selected: @document.doc_type),
    {prompt: :none}, {class: "form-select form-select-lg"}%>

    <%# We can customize prompt as what we want to show like this ::   prompt: "Select Document type" %>
    <%# <%= form.text_field :doc_type, class:"form-control"%> 
    <% @document.errors.full_messages_for(:doc_type).each do |message|%>
    <p class="text-danger"><%= message%></p>
    <%end %>
</div>
</div>


<div class=" d-grid d-md-flex justify-content-center">
<div class=" col-lg-6 mb-5">
    <%= form.label :employee_id %>



    <%# First is by Pluck in which we have to give attributes, method name will not work %>

<%# <%= form.select :employee_id, options_for_select(Employee.pluck(:F_Name, :id) selected: @document.employee_id), %>
    <%# {prompt: :none}, {class: "form-select form-select-lg"}%> 
    <%# <% @document.errors.full_messages_for(:employee_id).each do |message|%> 



    <%# Secondly by map %>
    <%# First we are giviving by name,  %>
<%# <%= form.select :employee_id, options_for_select(Employee.all.map {|employee| [employee.name, employee.id]},  selected: @document.employee_id),{prompt: :none}, {class: "form-select form-select-lg"}%> 
    <%# <% @document.errors.full_messages_for(:employee_id).each do |message|%> 



    <%# but name can be same, so we will define a name+mail method an show here  %>
     <%= form.select :employee_id, options_for_select(Employee.all.map {|employee| [employee.name_mail, employee.id]},  selected: @document.employee_id),{prompt: :none}, {class: "form-select form-select-lg"}%>
    <% @document.errors.full_messages_for(:employee_id).each do |message|%>



    <p class="text-danger"><%= message%></p>
    <%end %>
</div>
</div>

<div class=" d-grid d-md-flex justify-content-center">
<div class=" col-lg-6 mb-5">
<%=form.label :doc_upload %>  : 
<%= form.file_field :doc_upload ,class:"btn btn-sm"%>
</div>
</div>


<div class="row">
<div class=" d-grid d-md-flex justify-content-center">
<div class=" col-lg-6">
      <%= form.submit class:"btn btn-primary "%>
</div>
<div class=" d-grid d-md-flex justify-content-center">
<div class=" col-lg-6">
      <%= link_to "Back", documents_path,class:"btn btn-secondary"%>
</div>
</div>
</div>



  <%# </div> %>
  <% end %> 

hr-mitra/app/views/shared/_flash.html.erb
<div id="flash">
  <% flash.each do |key,value| %>
  <div class="<%= flash_class(key.to_sym)%> alert-dismisable fade show " role="alert">
    <% unless value == true %>
     <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
     <%= value%>
    <%end%>
</div>
  <%end%>
</div>

hr-mitra/app/views/shared/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->
<%# <div class="clearfix"> %>
<div class="container container-fluid height-auto   my-5">

  <footer class="d-flex flex-column vh-50", style="background-color: #6610f2">
  <!-- Grid container -->
  <div class="d-flex flex-grow-1">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright:
    <a class="text-white" href="http://localhost:3000/">Hr-mitra.com</a>
  </div>
  <!-- Copyright -->
</footer>
  
</div>
<%# </div> %>

hr-mitra/app/views/shared/_form.html.erb
<%= form_with model: @employee, local: true do |form|%>


<!--
<% if @employee.errors.any? %>
	<div class="col-lg-12">
	<%# <p class="lead">Please fix the below errors</p> %>
  <%#debugger%>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
  	    <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
			  <% end %>
      </ul>
    </div>
  </div>
<% end %>
-->




 <div class="form-group" >
<div class="row m-auto"  style="width: 90%;">
  <div class="col-md-5 ">
  <%= form.label :F_Name %>
  <%= form.text_field :F_Name, class:"form-control"%>
  <% @employee.errors.full_messages_for(:F_Name).each do |message|%>
  <p class="text-danger"><%= message%></p>
  <%end %>

    <%# <label for="inputEmail4" class="form-label">Email</label>
    <input type="email" class="form-control" id="inputEmail4"> %>

  </div>
  <div class="col-md-5">
    <%= form.label :L_Name %>
    <%= form.text_field :L_Name, class:"form-control"%>
    <% @employee.errors.full_messages_for(:L_Name).each do |message|%>
    <p class="text-danger"><%= message%></p>
    <%end %>
    

    <%# <label for="inputPassword4" class="form-label">Password</label>
    <input type="password" class="form-control" id="inputPassword4"> %>
  </div>
  </div>
 

 <div class="row mt-2 m-auto"  style="width: 90%;" >
 <div class="col-md-10">
    <%= form.label :Adreess%>
    <%= form.text_field :Adreess, class:"form-control"%>
    <% @employee.errors.full_messages_for(:Adreess).each do |message|%>
    <p class="text-danger"><%= message%></p>
    <%end %>
    </div>
  </div>

 <div class="row mt-2 m-auto"  style="width: 90%;">
  <div class="col-md-5">
  <%= form.label :Mail_Id %>
  <%= form.text_field :Mail_Id, class:"form-control"%>
  <% @employee.errors.full_messages_for(:Mail_Id).each do |message|%>
  <p class="text-danger"><%= message%></p>
  <%end %>

  </div>
  <div class="col-md-5">
    <%= form.label :Contact_No%>
    <%= form.text_field :Contact_No, class:"form-control"%>
    <% @employee.errors.full_messages_for(:Contact_No).each do |message|%>
    <p class="text-danger"><%= message%></p>
    <%end %>
    </div>
  </div>


  <div class="row mt-2 m-auto"  style="width: 90%;">
  <div class="col-md-5">
  <%= form.label :date_of_birth %>
  <%= form.date_field :date_of_birth, class:"form-control"%>
  <% @employee.errors.full_messages_for(:date_of_birth).each do |message|%>
  <p class="text-danger"><%= message%></p>
  <%end %>
  </div>

  <div class="col-md-5">
 <%= form.label :date_of_joining %>
  <%= form.date_field :date_of_joining, class:"form-control"%>
  <% @employee.errors.full_messages_for(:date_of_joining).each do |message|%>
  <p class="text-danger"><%= message%></p>
  <%end %>
  </div>
  </div>
  

  <div class="col-md-4 mt-4 mb-4 m-auto"  style="width: 90%;">
      <%= form.label :Department%>
      <%= form.select :Department, ["Select below option","Software Engineering","Quality Analyst","Human Resources","Finance","Administrattion"],{selected:['Select below option'],disabled: ['Select below option']}, {id: "Select"}  %>
      <% @employee.errors.full_messages_for(:Department).each do |message|%>
      <p class="text-danger"><%= message%></p>
      <%end %>
    
      <%# <select size="lg">
      <option selected>Choose...</option>
      <option>Software Engineering</option>
      <option>Quality Analyst</option>
      <option>Human Resources</option>
      <option>Finance</option>
      <option>Administrattion</option> %>
    <%# </select> %>
  </div>
  <%# <div class="col-12 mt-5 mb-5">
    <div class="form-check">

    <%= form.label :Check_me_out, class:"form-check-label"
    <%= form.check_box :check_box, class:"form-check-input"

    </div>
  </div> %>
  <div class="col-lg-12">
  <div class="col-md-12 mt-5 m-auto"  style="width: 90%;">
      <%= form.submit class:"btn btn-primary "%>
  </div>
    <%# <button type="submit" class="btn btn-primary">Sign in</button> %>
  <div class="col-md-12 d-grid d-md-flex justify-content-end m-auto"  style="width: 90%;  ">
      <%= link_to "Back", employees_path,class:"btn btn-primary"%>
  </div>
  </div>
  </div>
  <%# </div> %>
  <% end %>

hr-mitra/app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container-fluid">
    <%# <a class="navbar-brand" href="#">The Ruby</a> %>
    <%= link_to " Home ", root_path , class:"navbar-brand" ,target:"_blank"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-5 mb-lg-0">
        
        <li class="nav-item" style="color: rgba(0, 0, 0, 0.2);">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to " About Us " ,about_us_path,class:"nav-link", target:"_blank" %>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to " Contact " ,contact_path ,class:"nav-link", target:"_blank"%>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to " Privacy Policy " ,privacy_policy_path ,class:"nav-link", target:"_blank"%>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to " Conatct " ,contact_path ,class:"nav-link", target:"_blank"%>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to " Services " ,services_path ,class:"nav-link", target:"_blank"%>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to " Employee " ,employees_path ,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to " Documents " ,documents_path ,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to " HR_Graph " ,graph_employees_path ,class:"nav-link"%>
        </li>

        <% if user_signed_in?%>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Session
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Signed in as: <%= current_user.email %></a></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, class:"dropdown-item", method: :delete, data: { confirm:  "If you logout your current session will be expired,Are you sure you want to logout ??"}%></li>
          </ul>

        <%# In this we given the method name as delete as we have to destroy the session, if method name is not given by default it will take it as a get method and an error wiil come %>


        
        <%else%>
        <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class:"nav-link"%></li>
        <%end%>
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
            Dropdown
          </a>
          <%# <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul> %> 
    </div>
  </div>
</nav>